
* Modulo 1 - Formação Integral e Pensamento Complexo
** Quando falamos de Complexidade, sobre o que nos referimos?
• Sobre um modo de conhecimento que se gera de forma horizontal e
descentralizado, orientando-se por meio das interações que diversas
áreas da ciência estabelecem entre si;
• O pensamento Complexo critica os três pilares da racionalidade/ciência
moderna (Morin):
1. A Ordem;
2. A Separabilidade;
3. As lógicas dedutivas e indutivas.
** 1. A Ordem
• Um dos principais interesses da ciência sempre foi a busca pela ordem. A vida, porém,
não se movimenta por meio de fenômenos uniformes e totalmente previsíveis. Ela é
muito mais caótica do que a racionalidade linear pode considerar. Se a necessidade faz
parte da vida, dela também faz parte o acaso, a imprevisibilidade que foge de qualquer
determinação. A vida não segue um padrão mecanicamente elaborado e previamente
determinado, pois, se assim o fosse, a contingência não faria parte de sua natureza.
Mas, sabemos que o acaso, o aleatório faz parte dos acontecimentos de nossa vida
diária;
• Desta forma, compreende-se que a tônica de uma rígida racionalidade linear atrofia a
própria compreensão da realidade, tentando enquadrar a série de acontecimentos em
uma previa abstração dos fatos.
** 2. A Separabilidade
• Ao longo dos séculos a ciência concebeu que a melhor forma de estudarmos um determinado
objeto a ser pesquisado seria isolando-o e retirando-o de seu contexto;
• Desta forma, compreende-se que quanto mais separado de seu habitat o objeto está, mais
profícuo será o conhecimento obtido sobre ele. Compreendeu-se, assim, que a divisão de tal
objeto em inúmeras partes também seria relevante para o seu melhor conhecimento;
• Esse foi um fator importante no desenvolvimento científico e tecnológico da sociedade
ocidental;
• Ao dividir o saber em pequenas partes e estudá-las aprofundadamente foi possível um grande
avanço no conhecimento científico. Mas a especialização logo se revelou um beco sem saída.
Os cientistas, ao mesmo tempo que se aprofundavam na sua área de saber, perdiam também
o contato com o todo;
• A lógica da separabilidade fez com que ciência perdesse a noção do todo. As chamadas
“inteligências enciclopédicas”, pessoas que sabiam um pouco de tudo, se tornaram cada vez
mais raras.
** 3. Lógica Deudutiva e a lógica Indutiva
• Lógica Dedutiva: forma de raciocínio que se orienta por meio da dedução. Utilizando-se
de uma cadeia de raciocínio descendente, esta forma da racionalidade parte de uma
análise geral para a particular (Exemplo: Todos os homens são mortais. Sócrates é
homem. Então, Sócrates é mortal;
• Crítica: forma de racionalidade não experimental e abstrata em demasia;
• Lógica Indutiva: forma de raciocínio que se orienta por meio de generalizações.
Utilizando-se de algumas observações, esta forma de racionalidade parte de uma
análise particular para uma conclusão geral (Exemplo: Observação e registro de casos –
Conclusão – Formulação teórica sobre a observação realizada);
• Crítica: forma de racionalidade onde a conclusão é sempre genérica e imprecisa.

A proposta de Edgar Morin é
conceber uma nova forma de
racionalidade. Uma forma de
razão que seja dialógica, isto
é, pressuposta no diálogo e
na interação entre os
diferentes saberes.

** Educação Transdisciplinar
*** Cultura Interdisciplinar = Antropologia da Complexidade
• Um modelo de educação transdisciplinar só pode ser possível para uma pedagogia que
considere todas as dimensões humanas – raciocínio, respeito, afeto, crescimento, convivência,
interação, vinculo, acolhimento, potencialidade, cotidiano, contexto, etc.
• Aprender não apenas com a inteligência, mas também com o corpo e os sentimentos;
• Revolução da inteligência: equilíbrio entre inteligência analítica, sentimentos e corpos;
• A aprendizagem não apenas em seu aspecto formal, mas, também, trazendo para dentro do
seu bojo o lado lúdico do aprender!
• Não há uma receita pronta e milagrosa – o caminho se faz caminhando – não há uma
cartografia prévia do que será conhecido;
• Descentralização do saber / Centro Comum de questionamento (Mundo Globalizado);

Uma
racionalidade
que de conta
de uma outra
Antropologia
–
A
Complexidade
Humana

*** Ser Humano
• O Ser Humano é um ser biológico: dotado e constituído por uma natureza;
• O Ser Humano é um ser cultural: formado e formador de cultura/s;
• O Ser Humano é um Ser Multidimensional;
• Crítica as visões redutoras do humano e da vida – o cartesianismo, o patriarcalismo e a visão
newtoniana;
• Ampliação da noção de Ser Humano: contra reduções unidimensionais do Ser Humano, da
realidade e da vida;
• Cada um de nós é um universo de possibilidades. A flexibilidade nas relações e no pensamento
ampliam a possibilidade de ser;
• Trata-se, portanto, de desconstruir modelos e referências mentais que não se colocam em
relação de aprendizagem com o de fora e, de forma parcializada, fixam-se cegamente em
verdades, crenças e ideologias.

** Formação Integral
• Uma formação que contemple a formação lógica e racional, bem como, que também
erija e cuide da sensibilidade humana;
• A formação integral deve nos preparar para mantermos um equilíbrio entre uma razão
técnica e especializada e o desenvolvimento de nossa sensibilidade na constituição de
nossa subjetividade;
• Para isto devemos estar abertos ao desconhecido e não nos limitarmos a tradicional
zona de conforto – devemos perceber que o Ninho é um pedaço de nossa história, mas,
sempre nos lançamos ao mar. E devemos lembrar que este mar é imenso para
desenvolvermos a nossa potencialidade (para nos tornarmos aquilo que somos);
• A Formação Integral busca o crescimento humano múltiplo e diverso, bem como, o
reconhecimento do desenvolvimento de diferentes inteligências e habilidades.
Competência técnica e sensibilidade criativa associada a responsabilidade intersubjetiva
e ambiental sustentável.


* Módulo 2 - Visão Sistêmica e Ecologia Integral
** Visão Sistêmica
*** Pensamento Sistêmico:
• “Um sistema é um processo circular que, embora sob o aspecto
energético seja aberto para o meio ambiente, sob o aspecto
estrutural é fechado sobre si mesmo, que é estável, se retroalimenta,
se retrodetermina, se recompõe e se determina de maneira plástica a
partir de seu meio ambiente, que exerce seletividade em suas
interações para com este, que em muitos casos se replica ou
reproduz, que, quando afastado de seu ponto de equilíbrio, em
muitos casos, engendra novas formas de organização e de
comportamento, as quais se inserem em um processo de evolução”
(Cirne-Lima, Dialética e Auto-organização, p. 27-28);
• A visão sistêmica manifesta os limites do saber parcelar e
fragmentado;
• É a interação das partes que forma o todo – Holismo;
• Redes dentro de redes: em todas as escalas da natureza,
encontramos sistemas vivos alojados dentro de outros
sistemas vivos – os limites dentro dos sistemas são limites
de identidade;
• Assim como o ser humano, a natureza é complexa em sua
teia de relações. Não uma teia ordenada em que cada parte
exerce uma função definida, mas, uma rede de alianças
flexíveis, que nos coloca diante do tempo e da evolução
como seres desafiados a compor parcerias criativas.
*** Pensar em Redes:
• A questão não é o que podemos extrair da natureza, mas o
que podemos aprender com ela;
• Desenvolver e criar redes: interdependência entre o
cuidado de si (relação interpessoal), o cuidado com o outro
(relação intersubjetiva) e o cuidado com a natureza
(experiência terrestre);
• Cooperação e co-evolução (Maturana): as trocas de energia
e recursos materiais num ecossistema são sustentadas por
uma cooperação generalizada – formação de parcerias
flexíveis.
*** Sistemas de Rede são Interligados:
• Sistemas Interligados: Em todos os níveis de vida – desde as redes metabólicas dentro
da célula até as teias alimentares dos ecossistemas e as redes de comunicações da
sociedade humana -, os componentes dos sistemas vivos se interligam sob a forma de
rede. Vimos, em particular, que na Era da Informação – na qual vivemos – as funções e
processos sociais organizam-se cada vez mais em torno das redes. Quer se trate das
grandes empresas, do mercado financeiro, dos meios de comunicações ou das ONGs
globais, constatamos que a organização em rede tornou-se um fenômeno social
importante e uma fonte crítica de poder;
• O grande desafio do século XXI é da mudança do sistema de valores que está por trás
da economia global, de modo a torná-lo compatível com as exigências da dignidade
humana e da sustentabilidade ecológica;
*** Dois pontos de virada: Feminismo e Ecologia:
• Dentre os muitos movimentos populares que atualmente trabalham pela mudança social, o
movimento feminista e o movimento ecológico são os que defendem as mais profundas
transformações de valores – o primeiro pela redefinição das relações entre os sexos, o segundo
pela redefinição das relações entre os seres humanos e a natureza. Ambos podem contribuir
significativamente para a superação da nossa obsessão pelo consumo material.
• De acordo com a sabedoria chinesa, os valores yang tem que ser equilibrados pelos valores yin,
ou femininos – a expansão pela conservação, a competição pela cooperação e a consciência
centrada nos objetos por uma consciência centrada nas relações ou relacionamentos - o
movimento rumo a esse equilíbrio é muito compatível com a passagem do pensamento
mecanicista para o pensamento sistêmico e ecológico que caracteriza a nossa época.
• Mudança do pensamento e dos valores: da busca da felicidade através de bens materiais para
o encontro da mesma felicidade nos relacionamentos calorosos.

Crítica ao antropocentrismo e
a razão
dominadora/instrumental: a
vida não pode ser reduzida
pela razão instrumental que
concebe a natureza como um
objeto a ser manipulado.

** Sustentabilidade (economico, ambiental, social)
*** O que é sustentabilidade?
• Conceito de Sustentabilidade: Sociedade sustentável como sendo aquela que é capaz de
satisfazer suas necessidades sem comprometer as chances de sobrevivência das gerações
futuras;
• Desenvolvimento Sustentável: atender as necessidades do presente sem comprometer a
capacidade das gerações futuras de atenderem as suas próprias necessidades;
• Casa-Terra: onde o modo de vida de uma comunidade humana não prejudica a capacidade
intrínseca da natureza de sustentar a vida;
• As comunidades sustentáveis desenvolvem seus modos de vida no decorrer do tempo,
mediante uma interação contínua com outros sistemas vivos, tanto humanos quanto não-
humanos. A sustentabilidade não implica uma imutabilidade das coisas. Não é um estado
estático, mas um processo dinâmico de coevolução.
*** Alfabetização Ecológica:
• Compreensão dos princípios de organização, comuns a todos sistemas vivos, que os
ecossistemas desenvolveram para sustentar a teia da vida;
• Os sistemas vivos são redes autogeradores, fechadas dentro de certos limites no que
diz respeito à sua organização, mas abertas a um fluxo contínuo de energia e matéria.
• Essa compreensão sistêmica da vida nos permite formular um conjunto de princípios
de organização que podem ser chamados de princípios básicos da ecologia e usados
como diretrizes para a construção de comunidades humanas sustentáveis.
• Em específico, há seis princípios da ecologia que dizem respeito diretamente à
sustentação da vida: redes, ciclos, energia solar, alianças (parcerias), diversidade e
equilíbrio dinâmico.


* Módulo 3 - Inteligência Coletiva e Transdisciplinaridade
** Educação Transdisciplinar
*** Relembrando o que é transdisciplinaridade:
• Um modelo de educação transdisciplinar só pode ser possível para uma pedagogia que considere
todas as dimensões humanas – raciocínio, respeito, afeto, crescimento, convivência, interação,
vinculo, acolhimento, potencialidade, cotidiano, contexto, etc.
• Aprender não apenas com a inteligência, mas também com o corpo e os sentimentos;
• Revolução da inteligência: equilíbrio entre inteligência analítica, sentimentos e corpos;
• A aprendizagem não apenas em seu aspecto formal, mas, também, trazendo para dentro do seu
bojo o lado lúdico do aprender!
• Não há uma receita pronta e milagrosa – o caminho se faz caminhando – não há uma cartografia
prévia do que será conhecido;
• Descentralização do saber / Centro Comum de questionamento (Mundo Globalizado);
• Para este processo faz-se necessário compreender os passos do Relatório Delors: aprender a
conhecer, aprender a fazer, aprender a viver em conjunto e aprender a ser.
*** Relatório Delors
**** Aprender a conhecer
Aprender os métodos utilizados para distinguir o real
do ilusório e para este fim o espírito científico é
essencial! Ser capaz de estabelecer pontes. Pontes
entre os diferentes saberes, entre estes saberes e a
vida cotidiana e entre as nossas próprias
subjetividades. Busca-se, portanto, a formação de um
humano re-ligado e dotado de uma maior
flexibilização!
**** Aprender a fazer
Aquisição de uma especialização. Mas não uma
especialização excessiva e petrificada. Uma
especialização que domine uma técnica, porém,
que seja flexível o suficiente para estar ligada e
conectada a outras profissões. O aprender a
fazer exige também a criatividade para se fazer o
novo!
**** Aprender a viver em conjunto
Não é o mesmo que apenas tolerar o outro, fingir
escutar o outro permanecendo convicto da justeza
absoluta de suas próprias posições. Respeitar as
normas de convívio social exige uma validação que
perpassa a experiência interior de cada ser. Ou seja,
exige que cada um se reconheça a si mesmo na face
do Outro, como unidade aberta e pluralidade
complexa. Este é um aprendizado permanente.
**** Aprender a ser
Exige uma eterna aprendizagem de seus próprios
condicionamentos, sua harmonia ou desarmonia
na vida social, as fundações de suas convicções,
descobrir a sua existência. Exige uma relação
transpessoal - aprender a não tratar o Outro
como um objeto e reconhecê-lo como alguém
que constrói junto comigo o objeto.
** Inteligência Coletiva
*** Inteligência coletiva
• Desenvolvimento de formas de saber que são como ferramentas que buscam
aperfeiçoar e qualificar a vida e as relações de convivência;
• O espaço do saber emerge da forma singular através da sociedade da
informação e do acesso democrático aos saberes e da possibilidade de liberação
de canais de comunicação;
• Auto-organização: organizada não por um centro, mas, espontânea – um campo
que fomenta a cooperação, troca de ideias e o desenvolvimento social e
cultural;
• Inteligência Coletiva como uma memória compartilhada, tecida em conjunto e
auto-organizada;
• Inteligência Coletiva: processo colaborativo (amizade) e competitivo
(liberdade);
• É a partir do equilíbrio entre cooperação e competição que nasce a inteligência
coletiva.
• Modelos Rígidos não desencadeiam um processo
evolutivo;
• A diversidade e as conexões dinâmicas atestam isto;
• O diálogo e a abertura sempre fomentam o
crescimento, ao sair de si para falar com o outro,
onde ambos devem ser receptivos e propositivos;
• Assim, o saber se faz em conjunto e o pensamento
torna-se nômade, cidadão do mundo sem perder sua
identidade local;
• Mediador: Há muitas formas de organização e o desafio é
inventarmos todos juntos formas de organização que não sejam nem
anárquicas – onde não haveria nenhuma forma de cooperação –
nem demasiadamente rígidas, mas sim as que permitam otimizar a
capacidade de invenção das pessoas, suas competências, suas
experiências, suas memórias;
• Hoje, no entanto, desde o desenvolvimento do ciberespaço,
podemos observar ou mergulhar na inteligência coletiva da
humanidade quando navegamos na web, quando participamos de
um fórum de discussão em uma língua e depois de outro em outra
língua etc. De repente, esse ecossistema das ideias humanas torna-
se palpável e percebemos que participamos dele, que nós é que o
tornamos vivo.
*** Capitais de Inteligência Coletiva
**** Capital Físico e Técnico
**** Capital Cultural = memória
**** Capital Social = vínculos, confiança
**** Capital Intelectual:
essa inventividade (que não é a
relação das pessoas entre si, nem dos signos entre
si) é a relação das pessoas com as ideias.
• Nós oferecemos nossa energia, nossa atenção,
nossas emoções e em troca as ideias nos dão mais
capital social, mais capital cultural e mais capital
técnico.

* Módulo 4 - Cultura, Diferença e Diversidade
** Cultura e humanização
*** O que é cultura?
**** Semântica - Dois sentidos:
***** Antiguidade:
• cultura como cultivo da educação e da virtude. Expressão advinda do verbo
latino colere – Cuidado do humano com a natureza, com os deuses (culto), com a
educação e a formação;
• Cultura e natureza não se opõem – cultura como segunda natureza que complementa a
primeira através do cultivo;
***** Modernidade:
• sinônimo de civilização. Advinda do latim, civil, a expressão agora designa
resultados da formação ou educação dos seres humanos;
• Separação e oposição entre natureza (que se constitui por leis necessárias de causa e
efeito) e cultura (que se estabelece pela liberdade e pela razão);
• Cultura como a edificação das obras humanas manifesta por meio da civilização – cultura
torna-se sinônimo de história (transformação racional por meio das relações humanas
com e no tempo).
**** A(s) Cultura(s)
• Acepção antropológica: referência para o significado é o início das culturas;
• “Assim, para muitos antropólogos, a diferença homem-Natureza surge quando os
humanos decretam uma lei que não poderá ser transgredida sem levar o culpado à
morte, exigida pela comunidade: a lei da proibição do incesto, desconhecida pelos
animais.” (CHAUÍ, 2000, p. 3)
• A lei, portanto, institui uma ordem simbólica de três pilares:
1. Símbolo como restrição/permissão: atribuição de valores, as coisas, relações humanas
e acontecimentos;
2. Símbolo como instituição fenomenológica: representação e interpretação da realidade;
3. Fundação da sociabilidade: por meio de um conjunto de práticas lega comportamentos,
instituições e ações.
• Pluralidade do sentido: “(...) uma mesma sociedade, por ser temporal e histórica, passa
por transformações culturais amplas e, sob esse aspecto, antropologia e História se
completam, ainda que os ritmos temporais das várias sociedades não sejam os mesmos,
algumas mudando mais lentamente e outras mais rapidamente.” (CHAUÍ, 2000, p. 4)
**** Cultura como invenção da relação com o Outro:
• Definição conceitual: “(...) Cultura é a
maneira pela qual os humanos se
humanizam por meio de práticas que
criam a existência social, econômica,
política, religiosa, intelectual e
artística.” (CHAUÍ, 2000, p. 4)
*** A Cultura na Modernidade Líquida
**** Universo Contemporâneo
• Bauman: Cultura como ‘fábrica de ordem’ – estabelecimento e manutenção da
ordem social por meio da transmissão e da fixação de valores, sobretudo por
meio das instituições sociais;
• Bourdieu: Cultura no século XX reforça e garante as diferenças sociais
hierárquicas;
• Modernidade Sólida: cultura como formação (conserva como algo sólido) do
cidadão para o Estado-Nação / Modernidade Líquida: cultura como propósito
de formação de consumidores – cultura na lógica de mercado;
• Em um mundo caracterizado como constante aceleração e transformação –
líquido: a cultura torna-se um dispositivo de sedução dos sujeitos, objetivando
criar desejos e respectivas promessas de satisfação – sem, porém, saciá-las de
fato;
• Não há cidadão, apenas indivíduo consumidor.
**** Subjetividade Líquida
• Cultura – Moda: Identidade Camaleão, aptidão ao câmbio e pueril;
• Bauman: Iluminismo/Modernidade – Cultura Única e Universal;
• Bauman: Multiculturalismo/Modernidade Líquida – indiferença à diferença;
• Indiferença à Diferença: existe a desigualdade para que exista a diversidade
(inclusive de escolhas);
• Bauman / Multiculturalismo: termo que presta-se como uma escusa que
justificaria as privações sociais observadas entre as culturas, entendendo, por
exemplo, a desigualdade social como resultado da multiplicidade de escolhas;
• Problemas com o sentimento de segurança: o refúgio em comunidades não
retoma o sentimento de segurança – para Bauman, somente o intercambio
mútuo entre as diferentes culturas pode fazer com que logremos o alcance de
uma comunidade comum.
** Diferença e Diversidade
*** Para além do imediato e do determinismo:
• Ausência de reflexão: “(...) capacidade de pensar de forma alternativa seu
comportamento na relação consigo, com os outros, com a história, com a
cultura e o mundo, transforma o ser humano em um ser de experiência
poética e digno para pensar um projeto que dê um sentido de transcendência
à existência.” (PILZ, s/d. P, 1)
• Pré-concepção: “Há vozes e preconceitos que filiam-se a determinismos
defendendo que heranças biológicas podem determinar comportamentos
humanos, assim como durante a história humana algumas sociedades
chegaram a desenvolver teorias em que a natureza geográfica era
determinante na tradição comportamental.” (PILZ, s/d. P, 2)
*** O Projeto Moderno Civilizador e a abertura
• A sociedade é a condição de alienação e libertação humana: êxtase – sair fora
de si – distanciamento em relação ao próprio mundo em que se vive;
• Estranhamento: pausa no imediatismo;
• Etnocentrismo: tendência a valorizar de forma excessiva as referências morais
do próprio grupo – KKK (racismo e raceismo);
• O etnocêntrico não reconhece a diferença, pois está preso dentro do si mesmo
e/ou preso dentro de si mesmo – do idêntico;
• A abertura para o diálogo requer um processo do si para o outro;
• Modernidade: Cultura = Civilização / Quem são os civilizados?
• Dominação imperialista: como chamar de civilizadas sociedades imperialistas
que impuseram através de métodos violentos a sua cultura?
*** Uma Cultura de abertura em relação ao Outro
• Encontro como humanização das relações: aprendizagem em relação à
diferença e à alteridade;
• Habilidade do diálogo à diversidade;
• Cultura como o espaço simbólico no qual o ser humano dá sentido à vida em
relação uns com os outros: cultura mestiça;
• Mestiçagem: encontro com a diversidade cultural no propósito de miscigenar-
se, ou seja, promover o diálogo planetário entre as culturas;
• Miscigenação: reconhecimento do Outro – da diferença;
• Vitrô multicolorido: as cores se atravessam e se completam;
• Miscigenar a espécie humana, mantendo as singularidades de cada cultura e de
cada pessoa.

“A humanização é o processo pelo qual o
humano desenvolve sua criação, altera a
natureza através da instrumentalização e
do trabalho e, mais tarde e de forma
mais efetiva, pela arte criativa e com a
riqueza simbólica com que projeta um
sentido da vida e da existência.” (PILZ,
s/d. P. 6)


* Módulo 5 - Experiência Estética e Criatividade
** Razão e Emoção
• A experiência sensível constrói a nossa subjetividade no percurso de nossas
vidas;
• Aquilo que nos entrega sentido e entendimento, que nos afeta ou nos repulsa
molda nosso si mesmo;
• As experiências que desenvolvemos em nossas vidas (sentido e sentimento)
esculpem, pintam ou projetam nosso modo de ser;
• A relação com o viver (a experiência do percurso da vida) é estética;
• Ou seja, é como a construção de uma obra de arte;
• Exatamente por isso não podemos permitir que o sobreviver se sobreponha ao
viver;
• Pois, a civilização moderna separou prosa e poesia. A vida de trabalho foi
invadida pela prosa, enquanto a poesia se refugiou na vida privada, na busca da
felicidade através das férias propiciadas pelo cartão de crédito.
** A arte de viver
• Conforme, Epicteto a verdadeira filosofia é a arte de viver bem a vida;
• A filosofia só é praticada de modo autêntico por aqueles que a associam à ação
no mundo, visando a uma vida melhor para todos;
• O primeiro passo para viver com sabedoria é renunciar à vaidade;
• Contemple o mundo como os olhos de um recém-nascido – só sei que nada sei;
• A arrogância é a máscara mais banal da covardia;
• Observe o que está realmente acontecendo, não só o que você pensar estar
acontecendo, ou gostaria que estivesse acontecendo. Olhe e escute bem o que
se passa a sua volta;
• O legítimo sentimento de satisfação por se alcançar um objetivo meritório e
difícil de conquistar não deve ser confundido com arrogância, que se caracteriza
pela preocupação excessiva consigo mesmo e a falta de interesse pelo
sentimento ou assuntos dos outros.

“Não é por meio de técnicas que se consegue ter
uma vida florescente. Ninguém pode tapear a si
mesmo usando truques para viver uma vida bem
vivida. Também não adiantam coisas do tipo "cinco
regras práticas" ou os dogmas prescritos por
alguma figura carismática. Ter uma vida em
expansão depende da nossa resposta, da melhor
maneira que pudermos, àquilo que cabe
exclusivamente a nós. Viver uma vida
extraordinária significa elevar nossa estatura moral
cultivando nosso caráter.”

** Viver a vidacomo uma obra de arte
*** O que é uma obra de arte?
• Impossibilidade de definição unívoca da arte;
• Noção histórica:
• Antiguidade – no começo o belo era o que imitava a realidade visível, era o que
respondia o paradigma naturalista e realista de representação;
• Modernidade – arte como sublimação / sentimento da relação da razão com o
mundo;
• Moderno-tardio – sentimento singular / valor subjetivo;
• Contemporâneo – dimensão conceitual da arte;
• Utilidade da arte: toda a arte é perfeitamente inútil;
• Arte como experiência singular do espectador (artista, público e/ou crítico) com
a obra produz efeitos de sentido – a arte reflete o espectador e não a vida.
** Acontecimento/Experiência estética:
• Ao contrário de perguntar o que é arte ou se isso é uma obra de arte, vale tomar
em questão a experiência de algum objeto, situação, acontecimento ou
processo naquilo que ele tem em termos de potencial artístico;
• Atitude estética = abertura circunstancial ao mundo;
• A atitude estética é uma abertura, uma disponibilidade não tanto para o objeto
da arte ou para o acontecimento em si, mas para os efeitos que ele produz em
mim, na minha percepção, no meu sentimento;
• A catarse reflete quem sou diante do mundo;
• O juízo estético refere-se ao sentimento que esse objeto ou acontecimento
produz no sujeito;
• Nós somos nós e nossa circunstância – somos seres de encontro.
• Jogo de mútua interferência: a realidade não é mera exterioridade, mas algo
que me constitui tanto quanto eu a constituo;
• Ao entrar em jogo com o objeto ou o acontecimento, eles deixam de ser
exteriores ao sujeito e passam a constituir o campo da experiência. É aí que
começa a criação, a experiência estética;
• Qual é o critério para falarmos em experiência estética?
• Dois pontos – artista e público;
• Artista: domínio da técnica e poder de criação – competência de compreensão e
competência de expressão;
• O artista está aberto ao porvir, as experiências e experimentações – dotado de
discernimento, possui a capacidade de compreender aquilo que se passa –
tomada de consciência do algo que nos passa.
• Obra de arte como zona de confluência de possibilidade – campo de potência
ilimitado;
• A arte deve ser experimentada instância de convocação dos sujeitos
num jogo de conhecimento e reconhecimento;
• Experienciar – entrar no jogo aberto: deixar que a arte se desvele à você e
desvele você mesmo;
• A experiência é um canal infinito de possibilidades abertas diante da
imprevisibilidade entre obra e público;
• O exercício de compreensão como uma tomada de atenção sobre os efeitos que
a experiência pode produzir;
• A formação do sujeito fruidor consiste em explorar diferentes maneiras de
compreender a experiência, possibilitando uma abertura à diversidade de
sentidos do mundo (ou seja, de formas de sentir a realidade).
• Neste caso, como o experimento pauta-se pela tônica do encontro, percebe-se
que podemos ter experiências estéticas com qualquer coisa (ex: ready-made
de Duchamp e a arte conceitual);
• A experiência, por sua vez, é sempre um desvelamento de cada um;
• Exatamente por isso ela não pode ser mediada, não há guia na condução da
vida, pois, ela é uma experiência intraduzível e intransponível;
• Efeitos da experiência estética: são as modalidades das experiências que vão se
modificando com a própria história, cujo núcleo é sempre essa estranha
satisfação que resulta do reconhecimento da capacidade de construir, de
produzir sentidos que, quando a gente experimenta, ao mesmo tempo está
construindo e produzindo a gente mesmo;
• Não há esquemas referenciais – cada singularidade é uma forma de
subjetivação possível.


* Módulo 6 - Estética Profissional
** Terceira Onda
*** Terceira Onda
Enquanto que a primeira onda centra-
se na agricultura e a segunda na
indústria, a civilização da terceira
onda está centrada na gestão do
conhecimento e da informação.

Estes pilares, atualizam-se por meio
de redes de troca e não por formas
funcionais de comunicação.

Há, portanto, uma flexibilização nas
hierarquias que compõem uma
organização, um alargamento do espaço
onde o colaborador se coloca como um
agente propositivo das ações.

As formas de comunicação facilitam e
promovem diálogos em redes internas e
externas, promovendo, assim, a
qualificação das organizações.
*** O que representa esse advento da sociedade da informação?
“Por um lado, o perigo da banalização do saber, ou seja,
qualquer informação pode fazer a cabeça de alguém; por
outro, as pessoas podem reduzir sua navegação a buscas
somente daquilo que se enquadra em seu modelo e juízo
mental. Não é essa perspectiva otimista que queremos pensar
a partir de entradas e saídas que podemos compor a partir de
redes digitais, (...) profissionais diferenciados (...), uma
formação generalizada e de níveis cada vez mais sofisticados
possa fazer emergir uma sociedade de inteligência coletiva.”
** Formação Total
• Hibridização da Formação;
• A formação total deve preparar para o trabalho, para o estudo e para o tempo livre.
Mas, concebendo este tempo livre como ócio criativo e não como passatempo, tempo
perdido ou fluído no entretenimento superficial;
• Equilíbrio entre trabalho, estudo e lazer;
• A formação total se insere em um novo modo de vida / cultura pós-moderna: a
essência deste fator não se deve a um ou mais fenômenos, mas a um complexo
conjunto de novidades (tecnológicas, comportamentais, sociais, trabalho, etc.);
• Paradigma da Digitalidade: flexibilização das relações de teletrabalho (home-ofice),
Organização do trabalho por metas e objetivos;
• Substituição dos sistemas de controle por sistemas de motivação e Trabalho pós-
industrial não vende tempo, mas sim resultado.
** Desafios Profissionais/Trabalho Imaterial
*** Sociedade Pós Industrial
• Era Industrial = Produção Mecanizada;
• Ser Humano/Máquina: relação mecanicista;
• Lógica Industrial = Reprodução e Repetição;
• Era pós-industrial = mais fixada no processo de subjetivação;
• Era pós-industrial: subjetivação da atividade do trabalho;
• Era pós-industrial: interação entre ser humano e máquina;
• Lógica da produção pós-industrial: inovação e invenção;
• Há também um aumento na exploração do trabalhador, pois não se explora tão
somente o seu físico, mas o corpo como um todo, sua criatividade, sua
inteligência, suas habilidades, etc.
*** Trabalho Imaterial
• A nova fonte a ser explorada é a criatividade e o conhecimento;
• O capital na era pós-industrial investe na bios – na vida – do trabalhador;
• Sociedade pós-industrial: trabalhador comunicativo, participativo, polivalente,
flexível e, acima de tudo, dotado de um determinado conhecimento que
enriqueça o processo produtivo;
• Prescrição da subjetividade: o empregado assume voluntariamente os valores
da empresa na qual adere - engajamento;
• O tempo do não-trabalho confunde-se com o do trabalho – o capital demanda
um engajamento total do trabalhador – em sua totalidade, modo de ser;
• Sociedade industrial = o trabalho situa-se fora do trabalhador / Sociedade pós-
industrial = o trabalho invade toda a sua subjetividade, ele é interiorizado.
*** A Multidão
• A demanda pelo engajamento do trabalhador, a subjetivação, produz uma
resposta ao biopoder do capital;
• A exploração das potencialidades singulares cria uma base produtiva comum – é
neste espaço comum que se encontra a base da exploração (produção e
subjetivação), mas, ao mesmo tempo, cria a subjetividade de resistência que se
configura na multidão;
• O comum é a base da multidão e é a multiplicidade de subjetividades que dá
conteúdo à multidão;
• Cf. “Negri e Hardt, a multidão é um sujeito social internamente diferente e
múltiplo cuja constituição e ação não se baseiam na identidade ou unidade
(muito menos na indiferença), mas naquilo que tem em comum”.
• A multidão busca resgatar, tornar comum, os recursos imateriais apropriados
e/ou expropriados pelos donos do capital.
