* Oficina Aula 1
Esta oficina é de extrema relevância, pois servirá como base para as próximas atividades a serem feitas nas aulas que estão por vir. Vamos começar lendo com atenção a situação a seguir:

Lázaro deseja desenvolver um sistema para sua rede de hotéis no qual ele possa cadastrar seus clientes, realizando, assim, todo o gerenciamento de seu estabelecimento. Como primeira versão, Lázaro solicita que o sistema cadastre seus hóspedes, ou seja, que ele esteja possibilitado a receber dados pessoais dos visitantes.

Para que isso seja feito, é essencial que os seguintes passos sejam executados sequencialmente:



** Etapa 1
Primeiramente devemos abrir nossa IDE e criar um projeto do tipo Java, para que assim possamos codificar corretamente. Então vamos lá:

+ [X] Primeiramente, abra o Eclipse IDE para criar um projeto do tipo Java, para que você possa codificar corretamente;
+ [X] Crie um projeto Java (Java project) chamado Hotel;
+ [X] Crie, no projeto, um pacote chamado br.dell.modelos.

Com o projeto criado, podemos definir as classes do nosso programa. Vamos para o próximo passo.

 
** Etapa 2
+ [X] Crie a classe modelo responsável por armazenar os dados dos visitantes;
+ [X] Crie a classe modelo Hospede com os seguintes atributos:
  + [X] private long CPF;
  + [X] private long RG;
  + [X] private String nome;
  + [X] private int idade;
  + [X] private String endereço.
+ [X] Crie os métodos getters e setters dos atributos;
+ [X] Crie um método construtor sem parâmetros;
+ [X] Crie um método construtor que receba todos os atributos como parâmetros.

Ao finalizar a Etapa 2, você terá modelado a classe que representará os hóspedes. Agora, vamos para o próximo passo.

 
** Etapa 3
+ [X] Crie a classe Quarto com os atributos:
  + [X] private int numero;
  + [X] private Hospede hospede.
+ [X] Gere os métodos getters e setters dos atributos;
+ [X] Crie um método construtor que receba todos os atributos como parâmetros.

Feito isso, você terá criado a classe que representará os quartos do hotel.

 
** Etapa 4
+ [X] Crie uma classe chamada Principal, com o método main().
+ [X] Esta será a classe que será executada para testarmos o programa.
+ [X] Ela conterá a lógica do programa que será:
    + [X] Receber do usuário os dados do hóspede (instanciar um objeto da classe Hospede)
    + [X] Atribuir um quarto ao hóspede (instanciar um objeto da classe Quarto com um objeto da classe Hospede)
    + [X] Exibir todas as informações ao usuário;

+ [X] Instancie no bloco do método main() um objeto do tipo Hóspede, adicionando suas respectivas informações. Dica: use o método showInputDialog() para receber as informações;
+ [X] Ao criar um novo hóspede (instanciar um objeto do tipo Hospede), o sistema deve informar que o visitante foi cadastrado com sucesso. Use o método showMessageDialog() da classe JOptionPane;
+ [X] Instancie um objeto da classe Quarto, recebendo os dados por meio do método showInputDialog(). Dica: como a classe Quarto possui um atributo da classe Hospede, passe como parâmetro em seu construtor os dados necessários, recebidos do usuário, e o objeto da classe Hospede.

Feito isso, você terá desenvolvido um programa para receber as informações do usuário. Agora, precisamos exibi-las. Faremos isso na próxima etapa.

 
** Etapa 5
+ [X] Exiba, através do método showMessageDialog(), os dados do hóspede e o número do seu quarto.

Ao fim de todas as cinco etapas, você terá criado um programa que recebe como entrada as informações de um hóspede e o quarto em que ele ficará hospedado, exibindo essas informações para o usuário ao fim da execução.

 
